on: workflow_dispatch 
name: Manual Deploy website cpv2
jobs:
  web-deploy:
  
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies and build assets
      run: |
        cd assets
        npm install
        npm run build

    - name: Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.6
      with:
        server: 94.130.22.223
        server-dir: /cpv2.kmfoysal06.com/wp-content/plugins/charming-portfolio/
        local-dir: ./
        username: kmfoysa1
        password: ${{ secrets.password }}
